// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateMA(arg1, arg2, arg3) {
  return window['go']['main']['App']['CalculateMA'](arg1, arg2, arg3);
}

export function CalculateMACD(arg1) {
  return window['go']['main']['App']['CalculateMACD'](arg1);
}

export function DeleteExecutionRecord(arg1) {
  return window['go']['main']['App']['DeleteExecutionRecord'](arg1);
}

export function ExecuteStrategy(arg1) {
  return window['go']['main']['App']['ExecuteStrategy'](arg1);
}

export function GetDataUpdateStatus() {
  return window['go']['main']['App']['GetDataUpdateStatus']();
}

export function GetExecutionRecord(arg1) {
  return window['go']['main']['App']['GetExecutionRecord'](arg1);
}

export function GetExecutionRecords() {
  return window['go']['main']['App']['GetExecutionRecords']();
}

export function GetExecutionResults() {
  return window['go']['main']['App']['GetExecutionResults']();
}

export function GetExecutionState() {
  return window['go']['main']['App']['GetExecutionState']();
}

export function GetHistoricalTransactions(arg1) {
  return window['go']['main']['App']['GetHistoricalTransactions'](arg1);
}

export function GetIndexList() {
  return window['go']['main']['App']['GetIndexList']();
}

export function GetKLineData(arg1, arg2) {
  return window['go']['main']['App']['GetKLineData'](arg1, arg2);
}

export function GetRealtimeData(arg1) {
  return window['go']['main']['App']['GetRealtimeData'](arg1);
}

export function GetSchedulerStatus() {
  return window['go']['main']['App']['GetSchedulerStatus']();
}

export function GetStrategies() {
  return window['go']['main']['App']['GetStrategies']();
}

export function GetStrategyByID(arg1) {
  return window['go']['main']['App']['GetStrategyByID'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PauseExecution() {
  return window['go']['main']['App']['PauseExecution']();
}

export function ResumeExecution() {
  return window['go']['main']['App']['ResumeExecution']();
}

export function RunSchedulerNow() {
  return window['go']['main']['App']['RunSchedulerNow']();
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function StopExecution() {
  return window['go']['main']['App']['StopExecution']();
}

export function UpdateStockData() {
  return window['go']['main']['App']['UpdateStockData']();
}
