// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {indicators} from '../models';
import {data} from '../models';
import {engine} from '../models';
import {main} from '../models';
import {api} from '../models';
import {context} from '../models';

export function CalculateMA(arg1:Array<number>,arg2:string,arg3:number):Promise<Array<number>>;

export function CalculateMACD(arg1:Array<number>):Promise<indicators.MACDResult>;

export function DeleteExecutionRecord(arg1:string):Promise<void>;

export function ExecuteStrategy(arg1:number):Promise<void>;

export function GetDataUpdateStatus():Promise<data.UpdateStatus>;

export function GetExecutionRecord(arg1:string):Promise<engine.ExecutionResult>;

export function GetExecutionRecords():Promise<Array<engine.ExecutionRecord>>;

export function GetExecutionResults():Promise<main.ExecutionResults>;

export function GetExecutionState():Promise<engine.ExecutionStatus>;

export function GetHistoricalTransactions(arg1:string):Promise<Array<api.HistoricalTransaction>>;

export function GetIndexList():Promise<Array<api.Index>>;

export function GetKLineData(arg1:string,arg2:api.KLineFreq):Promise<Array<api.KLineData>>;

export function GetRealtimeData(arg1:string):Promise<api.RealtimeData>;

export function GetSchedulerStatus():Promise<{[key: string]: any}>;

export function GetStrategies():Promise<Array<engine.Strategy>>;

export function GetStrategyByID(arg1:number):Promise<engine.Strategy>;

export function Greet(arg1:string):Promise<string>;

export function PauseExecution():Promise<void>;

export function ResumeExecution():Promise<void>;

export function RunSchedulerNow():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopExecution():Promise<void>;

export function UpdateStockData():Promise<void>;
